server:
  port: 8091
spring:
  
  # application:
  #   name: product-service
  # cloud:
  #   config:
  #     uri: http://localhost:8081
  #     username: root
  #     password: s3cr3t
  # boot:
  #   admin:
  #     client:
  #       url: http://localhost:8086
  h2:
    console:
      enabled: true
    
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    spring.sql.init.platform: h2
    username: sa
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5P} %m%n"